pub fn o<T: ToOwned + ?Sized>(x: &T) -> T::Owned {
    x.to_owned()
}

#[macro_export]
macro_rules! declare_codegen {
    () => {
        g!("//! Auto generated by `{}:{}`", file!(), line!());
        g!();
    };
}
